### ISSUE TITLE
Checklist conférence 11.03.2019 · Matériel

### ISSUE THREAD

**Issue by olange** [petitatelier/web-components-primer#1]
### Every speaker

- [x] Computer + adaptateur alimentation secteur `DONE`
- [x] Adaptateur ordi⟶HDMI (x1 ou x2) `DONE`
- [x] T-shirt 😸 `DONE`

### Electricité

- [x] Câble court avec multiprise x1 `DONE`
- [ ] Enrouleur de câble x1

### Projecteur(s)

- [x] Projecteur + câble alimentation `DONE`
- [x] Pied du projecteur + plaque de fixation photo `DONE`
- [x] Longue rallonge pour chaque projecteur `DONE`

### Réseau · optionnel

- [x] Routeur 3G/4G + carte SIM `WONTFIX`
- [x] Abonnement mobile actif pour la carte SIM `WONTFIX`
- [x] Câble Ethernet CAT5 SFTP 20m `WONTFIX`

### Divers

- [ ] Scotch théâtre, pour couvrir câbles au sol qui sont dans passage
- [x] Echelle en alu `WONTFIX`

### Voir aussi

* #2 Checklist conférence 11.03.2019 · Implantation
