### ISSUE TITLE
Checklist conférence 11.03.2019 · Implantation

### ISSUE THREAD

**Issue by olange** [petitatelier/web-components-primer#2]
### Contenu

- [x] Review `default` diapo for every slide (audience storyboard)
- [ ] Can I Use: compléter ou enlever les colonnes Chrome Android et Mobile Safari
- [ ] Section 4. The Ecosystem of Web Components
- [x] Synchroniser identifiants du [ `‹wcp-select›`](https://glitch.com/edit/#!/wcp-summary?path=my-select.js) avec [`‹wcp-summary›`](https://glitch.com/edit/#!/wcp-summary?path=my-summaryjs) dans projet `wcp-summary`
- [x] Check TODOs

### Déploiement

- [x] Déploiement Firebase du slideshow `DONE` 11.03 OL
- [x] Changer ownership du repo `@olange/web-components-primer` à `@petitatelier` `DONE` 19.03
- [x] Impression des cartes avec URL et QR-code de l'URL du slideshow `WONTFIX`
- [x] Rendre publics les projets Glitch `wcp-summary` et `wcp-vega-histogram` `DONE` 11.03 OL
- [x] Add Glitch URLs to SW-precache-config `DONE` 18.03 OL

### Dispositif scénique

- [x] Ajuster résolution des écrans sur les ordis pour qu'elle soit identique partout
- [x] Ajuster perspective du projecteur dans slideshow – voir [public/styles.js#L47](../blob/master/public/styles.js#L47)
- [x] Ajuster taille du texte et des diapositives aux écrans/projecteurs – voir [public/styles.js#L44](../blob/master/public/styles.js#L44)

### Accès Wifi et Live-coding pour audience

- [x] Màj. credentials du WiFi au SDG `DONE` 11.03 OL
- [x] Màj. URL du slideshow live `DONE` 11.03 OL
- [ ] Rétablir refresh timeout (rajouter les attributs) à 7.5 sec
- [ ] Test lien Slack `#webcomponents-primer` avec Yannis
- [ ] Changer credentials Firebase du projet Slideshow à Web Components Primer
- [ ] Test authentification Firebase avec Yannis
- [x] Check que head dans Firebase pointe sur `I01`

### Voir aussi

* #1 Checklist conférence 11.03.2019 · Matériel
