### ISSUE TITLE
Publish a non-live version of the slideshow

### ISSUE THREAD

**Issue by olange** [petitatelier/web-components-primer#5]
### Actions

- [x] Remove LIVE chip from homepage `DONE` 18.03 OL
- [x] Reshuffle diapositives in individual slides `DONE` 18.03 OL
- [x] Live-code examples should fill available space `DONE` 18.03 OL see petitatelier/slideshow#3
- [x] Synch TOC with ‹wcp-summary› contents in live-coding examples on Glitch `DONE` 19.03
- [x] Synch TOC with slide titles of live-coding examples `DONE` 19.03
- [x] Complete transcript of live-coding examples 2 and 5 `DONE` 21.03 OL see #4
- [x] Fix bug of missing `default` attribute in slideshow controller `WONTFIX` 24.03 OL will refactor controls, see petitatelier/slideshow#12
- [x] Have the slideshow start without choosing a display `DONE` 18.03 OL
- [x] Add touch controls to navigate the slides `DONE` 24.03 OL swipe left/right + next/prev buttons
- [x] Build & deploy on Firebase Hosting `DOING` 19–22.03 OL
- [x] Notify Yannis / Geneva Web `DOING` 19.03 OL communiqué liens à Yannis, 22.03 indiqué qu'ils pouvaient être publiés
